# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nitish Jadia
tagline:          'My Brain Dump'
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:      'Pouring my thoughts out!'
url:              https://jadia.github.io
baseurl:          /

author:
  name:           'Nitish Jadia'
  url:            https://twitter.com/jadianitish

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jadia

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
